config/routes.rb
Rails.application.routes.draw do
  get 'articles/new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => 'homes#top'
  post '/articles' => 'articles#create'
  get '/articles' => 'articles#index'
  get '/articles/:id' => 'articles#show', as: 'article'
  get '/articles/:id/edit' => 'articles#edit', as: 'edit_article'
  patch '/articles/:id' => 'articles#update', as: 'update_article'
  delete '/articles/:id' => 'articles#destroy', as: 'destroy_article'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	attachment :image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def new
  	@article = Article.new
  end

  def create
  	article = Article.new(article_params)
  	article.save
  	redirect_to '/'
  end

  def index
    @article = Article.new
  	@articles = Article.all
  end

  def show
  	@article = Article.find(params[:id])
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    article = Article.find(params[:id])
    article.update(article_params)
    redirect_to article_path(article.id)
  end

  def destroy
    article = Article.find(params[:id])
    article.destroy
    redirect_to articles_path
  end

  private

  def article_params
  	params.require(:article).permit(:title, :body, :weather, :image)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
	def top
		
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/articles/edit.html.erb
<h1>編集画面</h1>
<%= form_for(@article) do |f| %>
    <h4>タイトル</h4>
    <%= f.text_field :title %>
    <h4>天気</h4>
	<%= f.text_field :weather %>
    <h4>本文</h4>
    <%= f.text_area :body %>
    <%= f.submit '保存' %>
    <h4>画像</h4>
  	<%= f.attachment_field :image %>

<% end %>

app/views/articles/index.html.erb
<div class="container-fluid">
<div class="row">
	<div class="col-md-4">
<!-- form_for部分 -->
<%= form_for(@article) do |f| %>

    <h4>タイトル</h4>
	<%= f.text_field :title %>

	<h4>天気</h4>
	<%= f.text_field :weather %>

	<h4>本文</h4>
	<%= f.text_area :body %>

	<%= f.submit '投稿' %>
	<h4>画像</h4>
  	<%= f.attachment_field :image %>
  	
  	<%= f.submit '投稿' %>
	</div>
<% end %>

<div class="col-md-8">
<table class="table">
	<thead>
		<tr>
			<th>タイトル</th>
			<th>天気</th>
			<th>本文</th>
			<th>画像</th>
		</tr>
	</thead>
	<tbody>
		<% @articles.each do |article| %>
		<tr>
			<td><%=link_to article.title,"/articles/#{article.id}" %></td>
			<td><%= article.weather %></td>
			<td><%= article.body %></td>
  			<td><%= attachment_image_tag article, :image, :fill, 100, 100, format: 'jpeg' %></td>
		</tr>
	</tbody>
	<% end %>
</table>
</div>
</div>

app/views/articles/new.html.erb
<h1>新規投稿</h1>

<%= form_for(@article) do |f| %>

	<h4>タイトル</h4>
	<%= f.text_field :title %>

	<h4>天気</h4>
	<%= f.text_field :weather %>

	<h4>本文</h4>
	<%= f.text_area :body %>

	<h4>画像</h4>
  	<%= f.attachment_field :image %>
  	
  	<%= f.submit '投稿' %>

<% end %>

app/views/articles/show.html.erb
<h2>タイトル</h2>
<p><%= @article.title %></p>
<h2>天気</h2>
<p><%= @article.weather %></p>
<h2>本文</h2>
<p><%= @article.body %></p>
<h2>画像</h2>
<%= attachment_image_tag @article, :image, :fill, 300, 300, format: 'jpeg' %>

<%= link_to "編集", edit_article_path(@article.id) %>
<%= link_to "戻る", "http://localhost:3000/articles" %>
<%= link_to "削除", destroy_article_path(@article.id), method: :delete, "data-confirm" => "本当に削除しますか？" %>

app/views/homes/top.html.erb
<h1>Ryota Ogiwara</h1>
<p>
	<%= link_to '新規投稿',"http://localhost:3000/articles/new" %>
</p>
<div class="box">
	<%=image_tag'avengers-iron-man.jpg',:size =>'800x700' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OgiwaraDiary</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>